Fix a Block.containsTouch method
it used to return null instead of false, which caused an exception down the callchain
Exception: type 'Null' is not a subtype of type 'bool' of 'boolean expression'.
Stack Trace: #0      TouchManager.findTouchTarget (/ComputerMuseum/Touch.dart:83:29)